/// Asset locations for the IndoPak Mushaf prototype.
///
/// All three files are downloaded from QUL (https://qul.tarteel.ai) by
/// `tool/fetch_qul_assets.sh` and bundled as assets. They are NOT committed
/// to the repository.
library;

class IndoPakAssets {
  IndoPakAssets._();

  /// QUL "Indopak 15 lines" mushaf-layout export (`pages` table).
  static const String layoutDb = 'assets/indopak/indopak_15_lines_layout.db';

  /// QUL IndoPak word-by-word script export (`words` table).
  static const String wordsDb = 'assets/indopak/indopak_words.db';

  /// QUL IndoPak Nastaleeq font (Hanafi), loaded at runtime via FontLoader.
  static const String font = 'assets/indopak/fonts/indopak_nastaleeq.ttf';

  /// Family name registered by [loadIndoPakFont].
  static const String fontFamily = 'IndoPakNastaleeq';
}

/// Thrown when the QUL assets have not been fetched yet.
class IndoPakAssetsMissingException implements Exception {
  const IndoPakAssetsMissingException(this.missingAsset);

  final String missingAsset;

  @override
  String toString() =>
      'QUL asset not bundled: $missingAsset. '
      'Run tool/fetch_qul_assets.sh and rebuild. Quran text is never '
      'generated by the app — it must come from the QUL database.';
}
